# Site settings
title: Random Hack of Kindness Ottawa
email: ottawa.rhok@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random Hacks of Kindness Ottawa organizes hackathons (events were we build 
  stuff) to help civic minded organizations be more awesome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rhok.ca" # the base hostname & protocol for your site
twitter_username: rhok_ottawa
github_username:  jekyll

# Build settings
markdown: kramdown
